### ISSUE TITLE
about supervised training dataset

### ISSUE THREAD

**Issue by Hanser14Forever** [McGill-NLP/llm2vec#58] opened 2024-05-08 03:09 UTC
Hi, I download data for supervised training from [here](https://github.com/jakespringer/echo-embeddings#training). But when i run your training code, allnli_split1.jsonl, allnli_split2.jsonl, quora_duplicates_split1.jsonl, quora_duplicates_split2.jsonl are missing. Where can I find them?

**Comment by vaibhavad** [comment] 2024-05-08 15:37
My apologies, I forgot to include a post-processing step, I'll change the code and fix it right away

**Comment by vaibhavad** [comment] 2024-05-08 16:33
The issue is fixed now. You should be able to run the code with the data that you downloaded. Please take the latest changes if you are building `llm2vec` from source, otherwise make sure `llm2vec` version from pip is `>=0.1.6`.

Apologies for the error again and let me know if you face any more issues

**Closed** 2024-05-09 16:16 UTC
