### ISSUE TITLE
Fine Tuning Script on Custom Data

### ISSUE THREAD

**Issue by WorldHellow** [McGill-NLP/llm2vec#109] opened 2024-06-26 09:45 UTC
Hello, I have a some Named Entity Recognition BIO Annotatotion style dataset and I was wondering if there are any scripts available that I can use for fine-tuning Token level classifier.

**Comment by vaibhavad** [comment] 2024-07-04 15:26
Closing as it is a duplicate of #112

**Closed by vaibhavad** 2024-07-04 15:26 UTC
